name: idb_sqflite_repo
description: idb_sqflite repo
version: 0.1.0
homepage: https://github.com/tekartik/idb_sqflite

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: null_safety
    version: '>=0.1.0'
  process_run: '>=0.10.1'
  dev_test:
  flutter_lints:


