name: idb_sqflite_repo
description: idb_sqflite repo
version: 0.1.0
homepage: https://github.com/tekartik/idb_sqflite

publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  process_run: '>=0.10.1'
  dev_test:
  flutter_lints:
  path:
  pub_semver:
  yaml:
