# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore errors like
    included_file_warning: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - no_adjacent_strings_in_list
    - omit_local_variable_types
    - package_api_docs
    - prefer_const_constructors
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - unsafe_html

